## Step 1: download the data from 2008

http://stat-computing.org/dataexpo/2009/the-data.html

In [11]:
import pandas as pd

df = pd.read_csv("/Users/jamiew/GA-DataScience/GA-MyDSRepo/lesson-7/2008.csv").fillna(0)

In [31]:
df2 = df.head(10000)

In [32]:
pd.options.display.max_columns = 999

df.head()

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0  2008      1           3          4   2003.0        1955   2211.0   
1  2008      1           3          4    754.0         735   1002.0   
2  2008      1           3          4    628.0         620    804.0   
3  2008      1           3          4    926.0         930   1054.0   
4  2008      1           3          4   1829.0        1755   1959.0   

   CRSArrTime UniqueCarrier  FlightNum TailNum  ActualElapsedTime  \
0        2225            WN        335  N712SW              128.0   
1        1000            WN       3231  N772SW              128.0   
2         750            WN        448  N428WN               96.0   
3        1100            WN       1746  N612SW               88.0   
4        1925            WN       3920  N464WN               90.0   

   CRSElapsedTime  AirTime  ArrDelay  DepDelay Origin Dest  Distance  TaxiIn  \
0           150.0    116.0     -14.0       8.0    IAD  TPA       810     4.0   
1           145.0    113.0       2.0      19.0    IAD  TPA       810     5.0   
2            90.0     76.0      14.0       8.0    IND  BWI       515     3.0   
3            90.0     78.0      -6.0      -4.0    IND  BWI       515     3.0   
4            90.0     77.0      34.0      34.0    IND  BWI       515     3.0   

   TaxiOut  Cancelled CancellationCode  Diverted  CarrierDelay  WeatherDelay  \
0      8.0          0                0         0           0.0           0.0   
1     10.0          0                0         0           0.0           0.0   
2     17.0          0                0         0           0.0           0.0   
3      7.0          0                0         0           0.0           0.0   
4     10.0          0                0         0           2.0           0.0   

   NASDelay  SecurityDelay  LateAircraftDelay  
0       0.0            0.0                0.0  
1       0.0            0.0                0.0  
2       0.0            0.0                0.0  
3       0.0            0.0                0.0  
4       0.0            0.0               32.0

### This dataset is WAY TOO BIG for the get_dummies function

+ Feel free to test it out and eventually use the "interrupt" function when you get bored
+ Hey maybe it still works? Who knows. It took a while for me. 

In [ ]:
pd.get_dummies(df[['TailNum', 'Origin', 'Dest']])

### Let's first investigate the String Vars here

In [33]:
df[['UniqueCarrier', 'TailNum', 'Origin', 'Dest', 'CancellationCode']].head(10)

UniqueCarrier TailNum Origin Dest CancellationCode
0            WN  N712SW    IAD  TPA                0
1            WN  N772SW    IAD  TPA                0
2            WN  N428WN    IND  BWI                0
3            WN  N612SW    IND  BWI                0
4            WN  N464WN    IND  BWI                0
5            WN  N726SW    IND  JAX                0
6            WN  N763SW    IND  LAS                0
7            WN  N428WN    IND  LAS                0
8            WN  N689SW    IND  MCI                0
9            WN  N648SW    IND  MCI                0

In [34]:
df['CancellationCode'].value_counts()

0    6872294
B      54904
A      54330
C      28188
D         12
Name: CancellationCode, dtype: int64

## We can use the Label Encoder to map the Strings to numbers!

+ THESE ARE NOT DUMMY VARIABLES
+ Note the fit vs fit_transform function

In [35]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

#le.fit(df['UniqueCarrier'].head(10)) #calling 'head' for the sake of expediency
le.fit(df['TailNum'].unique().tolist()[0:10])

#le.transform(df['UniqueCarrier'].head(10)) #transforms the number
le.transform(df['TailNum'].unique().tolist()[0:10]) #transforms the number


array([6, 9, 0, 2, 1, 7, 8, 4, 3, 5])

In [36]:
le = LabelEncoder()

le.fit_transform(df['TailNum'].unique().tolist()[0:10])

array([6, 9, 0, 2, 1, 7, 8, 4, 3, 5])

In [37]:
le = LabelEncoder()

#le.fit_transform(df['UniqueCarrier'].head(10))
le.fit_transform(df['UniqueCarrier'].head(10))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TASK: How can you transform all character variables into numbers? 

+ Take 10 minutes to work with your partner

In [39]:
df2[['TailNum', 'DepDelay']].apply(lambda x: str(x), axis=1) #str is not the fn

0       TailNum     N712SW\nDepDelay         8\nName: ...
1       TailNum     N772SW\nDepDelay        19\nName: ...
2       TailNum     N428WN\nDepDelay         8\nName: ...
3       TailNum     N612SW\nDepDelay        -4\nName: ...
4       TailNum     N464WN\nDepDelay        34\nName: ...
5       TailNum     N726SW\nDepDelay        25\nName: ...
6       TailNum     N763SW\nDepDelay        67\nName: ...
7       TailNum     N428WN\nDepDelay        -1\nName: ...
8       TailNum     N689SW\nDepDelay         2\nName: ...
9       TailNum     N648SW\nDepDelay         0\nName: ...
10      TailNum     N690SW\nDepDelay         6\nName: ...
11      TailNum     N334SW\nDepDelay        94\nName: ...
12      TailNum     N476WN\nDepDelay        -4\nName: ...
13      TailNum     N765SW\nDepDelay         0\nName: ...
14      TailNum     N420WN\nDepDelay         2\nName: ...
15      TailNum     N263WN\nDepDelay         9\nName: ...
16      TailNum     N286WN\nDepDelay        27\nName: ...
17      TailNu

In [45]:
#in-class assignment
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

#le.fit(df2[['TailNum','UniqueCarrier','Origin', 'Dest','CancellationCode']].unique().tolist()[0:10])
#le.transform(df2[['TailNum','UniqueCarrier','Origin','Dest','CancellationCode']].unique().tolist()[0:10])
char_to_num = df2[['TailNum', 'UniqueCarrier','Origin', 'Dest','CancellationCode']].apply(lambda x: le.fit_transform(x), axis=0)
char_to_num.head()

TailNum  UniqueCarrier  Origin  Dest  CancellationCode
0      413              0      22    61                 0
1      470              0      22    61                 0
2      217              0      23    10                 0
3      324              0      23    10                 0
4      253              0      23    10                 0

In [47]:
#this is to replace the headers with the labels
df2[['TailNum', 'UniqueCarrier','Origin', 'Dest','CancellationCode']] = df2[['TailNum', 'UniqueCarrier','Origin', 'Dest','CancellationCode']].apply(lambda x: le.fit_transform(x), axis=0)


In [ ]:
df2[['TailNum', 'UniqueCarrier','Origin', 'Dest','CancellationCode']].apply(lambda x: le.fit_transform(x), axis=0)

In [76]:
y = df2['DepDelay']

df.drop(['DepDelay'], axis = 1, inplace = True, errors = 'ignore')

In [77]:
float(df2['CRSDepTime']) #can't run float on a series - so you'll get an error

TypeError: cannot convert the series to <type 'float'>

In [78]:
df2['CRSDepTime'].apply(float) #using float as a proxy for a continuous variable

0       1955.0
1        735.0
2        620.0
3        930.0
4       1755.0
5       1915.0
6       1830.0
7       1040.0
8        615.0
9       1620.0
10       700.0
11      1510.0
12      1430.0
13       715.0
14      1700.0
15      1020.0
16      1425.0
17       745.0
18      1255.0
19      1325.0
20       705.0
21      1625.0
22      1840.0
23      1030.0
24       800.0
25      1455.0
26      1255.0
27      1925.0
28       635.0
29       730.0
         ...  
9970    1630.0
9971    1100.0
9972    1600.0
9973    2000.0
9974    1300.0
9975     800.0
9976    1200.0
9977     700.0
9978    1600.0
9979    1725.0
9980     600.0
9981    1830.0
9982    1905.0
9983    1150.0
9984    2040.0
9985    1440.0
9986     815.0
9987    1005.0
9988     920.0
9989    1335.0
9990     635.0
9991    1720.0
9992    1400.0
9993    1150.0
9994     905.0
9995    1955.0
9996    1620.0
9997    1805.0
9998    1430.0
9999    1050.0
Name: CRSDepTime, dtype: float64

In [79]:
df2['CRSDepTime'].apply(lambda x: float(x))

0       1955.0
1        735.0
2        620.0
3        930.0
4       1755.0
5       1915.0
6       1830.0
7       1040.0
8        615.0
9       1620.0
10       700.0
11      1510.0
12      1430.0
13       715.0
14      1700.0
15      1020.0
16      1425.0
17       745.0
18      1255.0
19      1325.0
20       705.0
21      1625.0
22      1840.0
23      1030.0
24       800.0
25      1455.0
26      1255.0
27      1925.0
28       635.0
29       730.0
         ...  
9970    1630.0
9971    1100.0
9972    1600.0
9973    2000.0
9974    1300.0
9975     800.0
9976    1200.0
9977     700.0
9978    1600.0
9979    1725.0
9980     600.0
9981    1830.0
9982    1905.0
9983    1150.0
9984    2040.0
9985    1440.0
9986     815.0
9987    1005.0
9988     920.0
9989    1335.0
9990     635.0
9991    1720.0
9992    1400.0
9993    1150.0
9994     905.0
9995    1955.0
9996    1620.0
9997    1805.0
9998    1430.0
9999    1050.0
Name: CRSDepTime, dtype: float64

In [57]:
df2.loc[:, 'CRSDepTime'] = df2['CRSDepTime'].astype(float)

/Users/jamiew/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:461: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


In [49]:
import numpy as np

(df.dtypes==np.int64).tolist()

df.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
DepTime              float64
CRSDepTime             int64
ArrTime              float64
CRSArrTime             int64
UniqueCarrier         object
FlightNum              int64
TailNum               object
ActualElapsedTime    float64
CRSElapsedTime       float64
AirTime              float64
ArrDelay             float64
Origin                object
Dest                  object
Distance               int64
TaxiIn               float64
TaxiOut              float64
Cancelled              int64
CancellationCode      object
Diverted               int64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

### Now as a replacement for get_dummies we have OneHotEncoder

+ BUT YOU NEED TO SPECIFY WHICH VARIABLES ARE CATEGORICAL
+ Could we use "integer" type as a proxy for that?

In [70]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(categorical_features = "all", sparse=False) #Boolean list. Sparse matrix - when u deal with large
#data sets - lots of zeros- might see a lot. Instead of storing the zeros. Some limitations w/what u do w Matrix

X =onehot.fit(df2[['UniqueCarrier', 'TailNum']])
X =onehot.transform(df2[['UniqueCarrier', 'TailNum']])
#X =onehot.fit_transform(df2[['UniqueCarrier', 'TailNum']])

#instead of just transforming one, it would be easier to feed it the entire data set. 


In [64]:
X 
# shape is most important. 10000 rows and 502 columns, which means 502 unique values between something and something else. 
#change sparse to False and get the whole matrix
#Every unique number in Tail Num has its own (driving most of it)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.]])

In [72]:
#different way to do it than what's shown above

from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(categorical_features = is_cat_list, sparse=True) #Boolean list. Sparse matrix - when u deal with large
#data sets - lots of zeros- might see a lot. Instead of storing the zeros. Some limitations w/what u do w Matrix

X =onehot.fit(df2)
X =onehot.transform(df2)
#X =onehot.fit_transform(df2[['UniqueCarrier', 'TailNum']])

#instead of just transforming one, it would be easier to feed it the entire data set. 

In [73]:
df2['TailNum'].nunique()

501

In [74]:
print X.shape

(10000, 3131)


In [75]:
import numpy as np

(df2.dtypes==np.int64).tolist()

is_cat_list = (df2.dtypes==np.int64).tolist()

In [68]:
is_cat_list #he explained a bunch of stuff here but I was typing off the screen and didn't hear what he said.

[True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False]

### Note that OneHot Encoder returns a sparse matrix

+ What is a sparse matrix?

In [ ]:
##This is how big the dataset is

X.shape

### Assignment part I - 15 minutes

+ Using a subsection of the full dataset...
    - (otherwise it will be impossibly large)
    - Create interaction variables for month and ArrDelay
    - Note that Month must first be a dummy variable
    - There are many ways to do this

### Assignment Part II

+ Run a Ridge regression with month dummies, arrival delay and the interaction vars
+ Keep track of the coefficients by saving the names to a list
+ Which variables are larger than zero? 
+ How does your model perform on the testing set?

In [64]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)


In [65]:
from sklearn import linear_model
lr = linear_model.Ridge(normalize=False)

In [80]:
lr.fit(X_train, y_train)

NameError: name 'lr' is not defined

In [ ]:
lr.score(X_test, y_test)